name: aerospike-client-go
dir: src/github.com/grossjo/aerospike-client-go

container:
  - base:
      - docker.qe.aerospike.com/build/golang:1.11

build:
  - name: build
    script:
      - go get -v github.com/grossjo/aerospike-client-go
      - go build -v -x github.com/grossjo/aerospike-client-go
      - go install -v -x github.com/grossjo/aerospike-client-go/tools/cli
      - go install -v -x github.com/grossjo/aerospike-client-go/tools/benchmark
      - go install -v -x github.com/grossjo/aerospike-client-go/tools/asinfo
